readings = {
    "Capricornio": [
        "Es probable que tu estado de ánimo sea hoy muy alegre y lo vas a mostrar en tu cara. Esto no va a pasar desapercibido para la gente que conoces. Puedes hacer algunos nuevos amigos y, si no tienes pareja, podrías conocer a alguien interesante y con potencial para el amor. Esta persona es alguien educado y refinado, por no mencionar inteligente. Sé cordial, agradable y disfruta de tu día.",
        "Es otro día en el que, potencialmente, sentirás mucha ansia. Sin embargo, tienes el poder de calmar tus ánimos. La actividad física de cualquier tipo te calmara considerablemente. Incluso una caminata rápida alrededor del bloque será beneficiosa. Una disposición más tranquila por la tarde hará que sea más fácil para ti manejar solicitudes y favores con tu gracia habitual. Si es necesario, puedes 'desaparecer' por unas horas a primera hora de la tarde y disfrutar de una película."
    ],
    "Aquario": [
        "Hoy es posible organizar una reunión de personas interesadas en cuestiones psíquicas o metafísicas. Un invitado muy especial podría dar una charla o liderar un grupo de discusión. Esto puede ser fascinante para todos los presentes. Te ganarás una gran reputación como anfitrión a pesar de que lo único que hagas sea pasar las galletas y servir el café. Por encima de todo, debes pasarla muy bien y disfrutar hablando con tus amigos. ¡Diviértete!",
        "Las aficiones y diversiones son una maravilla; nadie va a discutir esto contigo. Pero llega un momento en que utilizas tus aficiones como forma de evitar otras responsabilidades. Tus niveles intuitivos están tan altos como nunca. Tal vez puedes utilizarlos para tu propio beneficio. Trata de bloquear tus preocupaciones sobre los problemas mundanos del día a día para que puedas determinar por qué estás evitando las tareas que tienes que realizar."
    ],
    "Piscis": [
        "La escritura puede ser uno de tus principales actividades hoy. Tienes una gran cantidad de información para transmitir a cualquiera que pueda estar interesado en lo que tienes que decir. Podrías probar redactar un artículo para una revista o tal vez la ficción o la poesía. Sin embargo, incluso aunque todo lo que escribas en este momento sea una carta a tu primo, lo que digas, sin duda, será brillante, apasionante y muy interesante. ¡Manos a la obra!",
        "No hay duda de ello, ¡el cambio está próximo! Tal vez no puedes sentirlo porque te has permitido que la decepción te domine. No puedes dejar de preguntarte si alguna vez podrás alcanzar tus metas. Bueno, no te desanimes. Los tiempos están cambiando, como lo dice Bob Dylan. Sólo tienes que esperar un poco más. Al final, no importa lo mucho que tardes en llegar, ¡sólo que llegaste!"
    ],
    "Aries": [
        "Los intereses profesionales continúan expandiéndose y están logrando mantenerte muy ocupado/a. Tus ingresos están aumentando y podrías lograr una cierta importancia en tu campo. Sin embargo, podrías estar buscando nuevas oportunidades. Puede que el campo al que te dedicas ahora no sea en el que quieres continuar los próximos 20 años. Es por lo tanto un buen día para sondear las aguas. Puede que te sorprendan las oportunidades que hay.",
        "Todos los seres vivos se benefician de tus dones. El preocuparte de las cosas siempre ha sido parte de tu naturaleza, y es así especialmente hoy. Pero a veces prestas más atención hacia los demás que hacia ti, y esto no beneficia a nadie. Encontrarás que tendrás aún más de ti para dar cuando te tomes tiempo para llenar tu bienestar emocional. Algún tiempo lejos de las buenas obras será, en última instancia, beneficioso para todos, especialmente para ti."
    ],
    "Tauro": [
        "Un viaje en compañía de alguien cercano podría estar en el horizonte. De hecho, podrías irte muy pronto y probablemente la emoción esté aumentando. Algunos acontecimientos sorprendentes podrían surgir durante el transcurso de esta jornada, por lo que lo más probable es que esto llegue a ser algo más que unas simples vacaciones. Asegúrate de verte bien, no te detengas respecto a lo que quieres hacer y diviértete.",
        "En algún momento, la popularidad se convierte en una carga más que en una bendición. Te han llovido las invitaciones a conferencias y fiestas, pero no te entusiasma la idea de asistir a todos estos eventos. Quizá sea el momento para que puedas revaluar tus prioridades. En lugar de tratar de decir que sí a todo con el fin de complacer a todos, ¿por qué no empezar a decir que no para complacerte a ti mismo/a?"
    ],
    "Geminis": [
        "Un golpe de suerte inesperado podría llegarte hoy, - algo que nunca hubieras esperado ni en un centenar de años. Podría parecer como un sueño hecho realidad, sin embargo, podría afectar a tu vida de alguna manera. Podrías encontrarte frente a una decisión: ir por ella y cambiar tu modo de vida o dejarla pasar y aceptar el riesgo de que otra gran oportunidad nunca aparezca. ¿Quién dijo que la vida era fácil? Piensa en ello.",
        "Es otro día afortunado para las finanzas, así que asegúrate de aprovecharte de las oportunidades que se te presenten. Aunque con tu habitual estilo analítico, tendrás cuidado de realizar primero una revisión exhaustiva de los pros y los contras de la propuesta. Por mucho que te beneficie el estar trabajando hoy, no te olvides de salir a la calle para despejar tu mente. Sé especialmente consciente de los pensamientos o ideas que vienen de fuera, aparentemente de la nada."
    ],
    "Cancer": [
        "Si actualmente no estás en una relación sentimental, hoy puedes conocer a alguien que promete mucho. Tu trabajo podría estar involucrado de alguna manera, y también es posible que esta persona haya estado viviendo cerca durante mucho tiempo. Un amigo podría presentarles. Probablemente van a pasar al menos una hora hablando, y es probable que hagan arreglos para verse de nuevo.",
        "Estás viendo un nuevo lado de ti mismo/a hoy y lo bueno que es. Normalmente eres una persona conservadora, hoy te encuentras pensando en comprar ropa con detalles elegantes y tejidos caros. ¿Y por qué no? Sólo se vive una vez después de todo. Y el romance está definitivamente en el aire hoy, por lo que cualquier compra sexi o sensual que realices necesita encontrar un público."
    ],
    "Leo": [
        "Todos somos crédulos hasta cierto punto. Tú no eres una excepción. Puedes esperar recibir algunas ofertas financieras hoy. Pueden venir a través del correo electrónico o a través de una persona de ventas. Confía en tus instintos. Algo de lo que se está ofreciendo en realidad puede ser demasiado bueno para ser verdad. Sin embargo, lo que se te ofrece en casa es genuino por los cuatro costados. Hay pasión en el aire junto con toda esta integridad.",
        "Una especie de sacudida inesperada podría tener lugar hoy, y podrías encontrarte de repente que te ofrecen más dinero o responsabilidades. Esta puede ser justo la oportunidad que has estado esperando, pero podría tomarte tan de sorpresa que puede que tengas que pedir tiempo para pensar en ello. No lo pienses demasiado, ya que podrían darle la oportunidad a alguien más."
    ],
    "Virgo": [
        "Hoy puede que asistas a por lo menos una ocasión social festiva y, por lo tanto, puedes encontrarte con algunas personas muy interesantes en profesiones inusuales, tales como el cine o la televisión. Espera escuchar algunas historias extrañas, algunas de ellas ciertas, otras que son claramente exageradas. Sin embargo, de todas estas bromas y cuentos, podrías obtener alguna información útil. Toma nota de ello para que seas capaz de recordarlo más tarde.",
        "Tu sensibilidad ha aumentado en este momento y sabes cómo usarla. Si bien puede ser difícil que otras personas te necesiten tanto, ahora es tu turno prestar ayuda donde más se necesita. Te has preparado para la tarea en cuestión, por lo que ¿por qué no ofrecerte de todo corazón? Al final, cosecharás grandes recompensas por tus esfuerzos altruistas. Mientras tanto, puedes sentirte bien en relación a todo lo bueno que estás haciendo."
    ],
    "Libra": [
        "Es probable que tu nivel de salud y bienestar físico sea muy alto, y por lo tanto es probable que brilles intensamente. Como resultado, podrías encontrar que los que te rodean presten más atención a lo que dices de lo que lo suelen hacer. También descubrirás que tu mente es muy fuerte y que eres capaz de ser excepcional rapidez y captas las cosas a la primera. Por lo tanto, puedes absorber mucho más de lo que oyes que lo normal. ¡Toma nota de ello!",
        "Tu calidez y buena naturaleza atraen hoy a la gente hacia ti como un imán. Por supuesto, esto no es nada nuevo, pero hoy estos aspectos de tu persona se incrementan especialmente. Encontrarás que los encuentros con otras personas te hacen sentir plenitud y satisfacción. Después de todo, son nuestros seres queridos los que realmente hacen que la vida sea digna de ser vivida. Este momento es propicio para los encuentros románticos."
    ],
    "Escorpio": [
        "Es posible que hoy sientas pereza. Las mismas calles y edificios antiguos de la misma ciudad de siempre de repente podrían parecer que se acercan a ti. Por lo tanto, simplemente toma a un amigo cercano o a tu pareja, agarren el auto y despeguen hacia las montañas o el océano. Probablemente necesites un descanso. Has estado trabajando muy duro y probablemente podrías beneficiarte de un poco de tiempo en campo abierto. ¡Ve por ello!",
        "No hay duda de que esto se ha hecho esperar. Pero es probable el cambio que has estado esperando durante tanto tiempo tenga lugar hoy. Puede que la magnitud del cambio no sea obvia, al menos al principio. Pero con el tiempo, mirarás de nuevo hacia los acontecimientos de hoy y verás lo fundamental que eran. Guárdate tus opiniones para ti y aprovecha cualquier oportunidad interesante que se presente."
    ],
    "Sagitario": [
        "Un sueño o visión intensa podría resultar en un avance espiritual de algún tipo y es posible que pases gran parte del día un poco aturdido/a, tratando de sacarle algún sentido. Es posible que veas si puedes encontrar algunos libros sobre el tema, ya que todas las señales indican que la lectura podría traer una gran cantidad de información útil para la agenda de hoy. También puede ser que desees escribir un relato sobre tu experiencia.",
        "Es momento de cuidar de ti, en el verdadero sentido de la palabra. Esto no significa entregarte a excesos, sino más bien todo lo contrario. Haz un esfuerzo extra a la hora de vestirte y arreglarte. Calla esas voces interiores que te dicen que no te ves tan bien como deberías. ¡Te ves muy bien y después de esos cuidados especiales te verás mucho mejor!"
    ]
};
